version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    hostname: ${HOSTNAME}
    environment:
     - PMA_ARBITRARY=${PMA_ARBITRARY} | 1
    restart: always
    volumes:
     - sessions:/sessions
